name: Bug Report
title: "[BUG] "
description: Report a problem you're experiencing with Chevstrap.
body:
  - type: input
    id: version
    attributes:
      label: Chevstrap Version
      description: What version of Chevstrap are you using?
      placeholder: "v..."
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What problem did you encounter?
      description: Provide a detailed description of the issue. Include any relevant logs, screenshots, or other supporting materials.
    validations:
      required: true

  - type: textarea
    id: repro-steps
    attributes:
      label: How can we reproduce the problem?
      description: List all the steps needed to reproduce the issue. Mention any FastFlags or settings you modified.
      placeholder: |
        1. Open Chevstrap
        2. Go to '...'
        3. Click on '...'
        4. Observe the issue

  - type: input
    id: exception
    attributes:
      label: Chevstrap Exception (if any)
      description: If you're seeing a Chevstrap exception error, please upload your log file or describe the exception here. Leave blank if not applicable.
      placeholder: "N/A"
