name: Bug Report
title: "[BUG] "
description: Report a problem you're experiencing with Chevstrap.
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Acknowledgement of preliminary instructions
      options:
        - label: I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
          required: true
        - label: I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
          required: true
        - label: I am using the latest version of Chevstrap.
          required: true
        - label: I did not answer truthfully to all the above checkboxes.
  - type: input
    id: version
    attributes:
      label: Chevstrap Version
      description: What version of Chevstrap are you using?
      placeholder: "v..."
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What problem did you encounter?
      description: Provide a detailed description of the issue. Include any expection, screenshots.
    validations:
      required: true

  - type: textarea
    id: repro-steps
    attributes:
      label: How can we reproduce the problem?
      description: List all the steps needed to reproduce the issue. Mention any FastFlags or settings you modified.
      placeholder: |
        1. Open Chevstrap
        2. Go to '...'
        3. Click on '...'
        4. Observe the issue

  - type: input
    id: clone-app
    attributes:
      label: Are you using a clone app?
      description: If you're running Chevstrap inside a clone app, type the name here. If not, just leave it blank or write "N/A".
      placeholder: "..."
